version: '2'
services:
    openlearn-app:
        image: openlearn
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://openlearn-mysql:3306/openlearn?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JBOOTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=openlearn-elasticsearch:9300
    openlearn-mysql:
        extends:
            file: mysql.yml
            service: openlearn-mysql
    openlearn-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: openlearn-elasticsearch
